### ISSUE TITLE
Keep getting 'Property 'autocomplete' does not exist on type 'GooglePlaces'.

### ISSUE THREAD

**Issue by rw3iss** [mcabs3/google-places-web#12]
`
import Places from 'google-places-web';
Places.apiKey = '...';
let partialAddress = '1600 Pennsylv';
const radius = 2000;
const language = 'en';
// Search with default opts
Places.autocomplete({ input: partialAddress, radius, language })
  .then(results => {
    // results array of partial matches
  })
  .catch(e => console.log(e));
`

Compiling with webpack+TypeScript keeps giving:
TS2339: Property 'autocomplete' does not exist on type 'GooglePlaces'.

**Comment by mcabs3** [comment]
Sorry for the delay, I will address this. Thanks!
