### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by jedrichards** [mcabs3/google-places-web#14]
Just tried installing this and using in a create-react-app `2.0.3` app and got the following errors:

```
Error: Cannot find module 'axios'
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

As an aside, I'm not sure adding `axios` as a dependency to this web module is the right approach since it adds a lot of bloat for users not using axios as their http lib. Maybe using `fetch`, and letting users polyfill for it if needed, would be a better idea?

**Comment by mcabs3** [comment]
@jedrichards thanks for reporting, I will look into the issue and see what is up. I know CRA 2.0 is a new release so there will be some things to iron out.

**Comment by mcabs3** [comment]
@jedrichards I think that has been resolved with the newest version. Let me know if you still have issues.
