### ISSUE TITLE
Webpack import

### ISSUE THREAD

**Issue by beit46** [mcabs3/google-places-web#19]
Hello developers,

thanks for the amazing wrapper. Unfortunately, I can't get this to work. I am using webpack and trying to import with ES6.
This is the warning I get from webpack. When I try to import on my vuejs module I get an error and I'm unable to use it. Any ideas?

WARNING in ./node_modules/google-places-web/dist/index.js
33:12-23 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/google-places-web/dist/index.js
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}],"react","env","react","stage-2"],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/components/map/MapSearch.vue
 @ ./resources/components/map/MapSearch.vue
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}],"react","env","react","stage-2"],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/components/map/page/MapContent.vue
 @ ./resources/components/map/page/MapContent.vue
 @ ./resources/components/home/OrchestraRoutes.js
 @ multi ./resources/components/home/OrchestraRoutes.js

WARNING in ./node_modules/google-places-web/dist/index.js
34:17-34 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/google-places-web/dist/index.js
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}],"react","env","react","stage-2"],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/components/map/MapSearch.vue
 @ ./resources/components/map/MapSearch.vue
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}],"react","env","react","stage-2"],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/components/map/page/MapContent.vue
 @ ./resources/components/map/page/MapContent.vue
 @ ./resources/components/home/OrchestraRoutes.js
 @ multi ./resources/components/home/OrchestraRoutes.js
[Browsersync] Reloading Browsers... (buffered 209 events)

 WARNING  Compiled with 2 warnings                                                                                             20:13:07

 warning  in ./node_modules/google-places-web/dist/index.js

33:12-23 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

 warning  in ./node_modules/google-places-web/dist/index.js

34:17-34 Critical dependency: the request of a dependency is an expression

**Comment by mcabs3** [comment]
I will take a look, sorry you are having issues with it. I apologize.

**Comment by mcabs3** [comment]
Can you try updating your package.json to

``"google-places-web": "https://github.com/mcabs3/google-places-web.git"`

That has the latest commit and see if that addresses this issue. I was originally using parcel to build this utility but clearly either I don't understand it or can't get it to play nice :)

Either way, please let me know if this addresses your issue.

**Comment by beit46** [comment]
Thanks a lot for the support, super appreciated. 
I'll get on this and let you know, expect an answer by this Friday.

**Comment by beit46** [comment]
hey @mcabs3 I tried and the warnings are gone, and I can import the framework without errors. 
Now when I try to do an Places.autocomplete I got a CORS error, is there something missed on my side?
<img width="1859" alt="Screen Shot 2019-05-08 at 17 14 13" src="https://user-images.githubusercontent.com/2069373/57386540-d69a5000-71b4-11e9-8571-20c2d5a27ce5.png">

**Comment by mcabs3** [comment]
@beit46 where are you using this library (React Native, Node web server, etc)? CORS usually reflects your servers communication to google's server. Not something necessarily controlled by the library.

**Comment by beit46** [comment]
I am using this into a VueJS frontend, so it’s server unrelated.

**Comment by mcabs3** [comment]
@beit46 this library was created as a server side, this doesn't use the Google Maps JS library that handles the authentication for you on the front end so I think that is why you are seeing those CORs issues.
