### ISSUE TITLE
Error: Cannot find module 'superagent' - React

### ISSUE THREAD

**Issue by SharlSherif** [mcabs3/google-places-web#20]
I got that error while importing the package in React using this code :
```
import Places from 'google-places-web'

Places.apiKey = 'mykey'
Places.debug = true // boolean;

let partialAddress = '1600 Pennsylv'
const radius = 2000
const language = 'en'

// Search with default opts
Places.autocomplete({ input: partialAddress, radius, language })
  .then(results => {
    console.log(results)
    // results array of partial matches
  })
  .catch(e => console.log(e))
```
![image](https://user-images.githubusercontent.com/29375572/56645045-2c331080-667d-11e9-9644-ca50a9e58689.png)

i tried installing the `superagent` package but still

**Comment by mcabs3** [comment]
Can you try updating your package.json to

``"google-places-web": "https://github.com/mcabs3/google-places-web.git"`

That has the latest commit and see if that addresses this issue. I was originally using parcel to build this utility but clearly either I don't understand it or can't get it to play nice :)

Either way, please let me know if this addresses your issue.

**Comment by krsilas** [comment]
Hey, would you mind updating your package in the npm registry? The workaround causes issues in my production environment.

**Comment by mcabs3** [comment]
@krsilas I have updated the registry, please let me know if you have anymore issues.
