### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by jwjordan** [mcabs3/google-places-web#21]
I hope I'm not missing something simple, but is there a way to handle the pagetoken pagination?  The API wants the "next_page_token" value from the initial 20 results response to be passed as the "pagetoken" param on the next call.  I can't see how to access the "next_page_token" response value.  Is there a way to do this?  Thanks for any help you can provide.

**Comment by mcabs3** [comment]
Hi @jwjordan I don't think I currently have that implemented, however I will take a look and see if I can get that in for you. You are more than welcome to open a PR if you are interested in cloning and addressing the issue yourself.

**Comment by mcabs3** [comment]
@jwjordan I have completed this update and will get it into nom today.

**Comment by mcabs3** [comment]
@jwjordan when you get a chance. I pushed up my new commits for 1.0 into master. Give that a try and let me know.
