### ISSUE TITLE
How to pass params to details api other than place id?

### ISSUE THREAD

**Issue by dhwanilvyas** [mcabs3/google-places-web#25]
The google place details API supports passing in `fields` parameter to specify fields required in the response. How do I do that in this library? I don't see any option other than passing place id in the params.

**Comment by mcabs3** [comment]
@dhwanilvyas if you could try pointing to the latest commit in master, I have updated the library to include the fields parameter. When you are creating the params for your `.details()` call. you will be able to supply the `fields` property as you would in the web. 

ex. `.details({ placeId: '...', fields: 'address_component,name,geometry' })`

**Comment by dhwanilvyas** [comment]
Got it thanks! 😄
