### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by pkmAtgit** [mcabs3/google-places-web#26]
from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by mcabs3** [comment]
This sounds like it may be a configuration issue from the server app you are using this in, do you have more context on where you are using this library?

**Comment by mcabs3** [comment]
Closing because of no response.

**Comment by broskees** [comment]
I'm having this issue too, any idea what this would be caused by?

**Comment by broskees** [comment]
@mcabs3

**Comment by mcabs3** [comment]
This is usually an issue with the server where you are using it.

Can you give me more context on your setup? Express?

**Comment by mcabs3** [comment]
@broskees

**Comment by broskees** [comment]
No I was trying to use this in a browser not on a node server. I'm just dumb no worries.
