### ISSUE TITLE
NearbySearch param "Radius" is required

### ISSUE THREAD

**Issue by HashbangGames** [mcabs3/google-places-web#28]
Radius  is a required param and cannot be omitted when using rankby:"DISTANCE".

![image](https://user-images.githubusercontent.com/311188/72903873-dc07de00-3ce2-11ea-85e9-7f6ec8a3af8b.png)

**Comment by mcabs3** [comment]
Good catch, I will work on an update, I apologize for the delay.

**Comment by mcabs3** [comment]
@HashbangGames I have implemented this change into the latest commit. Can you try updating your package.json to point to this commit and seeing if this addresses your issue?

**Comment by HashbangGames** [comment]
Sorry for the delayed response! I never got around to testing this.. But i'm sure it works better now.  I worked around the issue for my code but I have not touched that project in a few weeks! Sorry!
