### ISSUE TITLE
INVALID_REQUEST error when attempting to use a pagetoken with NearbySearch API

### ISSUE THREAD

**Issue by ablankenship10** [mcabs3/google-places-web#30]
Apologies as I can't really add much more information other than I set these parameters for a follow up call to nearbyplaces and I get back this fairly useless error from their API.

```
 {
  radius: 50000,
  pagetoken: 'NEXT_TOKEN_FROM_PREVIOUS_CALL',
  location: '23,-110'
}

```

The API states that all other fields are ignored when making a call with a pagetoken but the library requires that I include location and radius. Tried setting params to only the page token right before the request is made in Places.js before the call to this._googleApiRequest() to no avail.

**Comment by mcabs3** [comment]
Hi @ablankenship10 I will take a look and see whats up.

**Comment by mcabs3** [comment]
Hey @ablankenship10 I actually ended up starting a V2 branch with some updates I had been wanting to do for a while. I did also address your issue with the current implementation. Do you mind plugging that branch in and seeing if that addresses your issue?
