### ISSUE TITLE
Need help with getting access to body

### ISSUE THREAD

**Issue by PradyMagal** [mcabs3/google-places-web#33]
So this is what my code looks like:

```javascript
function search(){
     try {
    const response = places.nearbysearch({
      location: text, // LatLon delimited by ,
      radius: distance,  // Radius cannot be used if rankBy set to DISTANCE
      type: ['cafe','bakery','meal_delivery','meal_takeaway','restaurant'], // Undefined type will return all types
      // rankby: "distance" // See google docs for different possible values
    });

    const { status, results, next_page_token, html_attributions } = response;
    console.log(tester);
    // console.log(test.data.json());
  } catch (error) {
    console.log(error);
  }


 }
```

In the console, it works great it displays all of the correct results, but I have one problem: getting the response body and storing the results in strings.

I have tried `response.results` and `response.body`, `response.json()`, and quite a few others but the variable returns undefined...
A little help?

**Comment by mcabs3** [comment]
Can you provide some information about your environment?

- JS/TS?
- Server/Web/Mobile?
- OS?

**Comment by PradyMagal** [comment]
Yea, I am developing this for mobile on Ubuntu...
I use the expo app on my phone to run the app

**Comment by PradyMagal** [comment]
Also lemme update the code I copied and pasted it wrong:
`
const results = null;
 function search(){
     try {
    const response = places.nearbysearch({
      location: text, // LatLon delimited by ,
      radius: distance,  // Radius cannot be used if rankBy set to DISTANCE
      type: ['cafe','bakery','meal_delivery','meal_takeaway','restaurant'], // Undefined type will return all types
      // rankby: "distance" // See google docs for different possible values
    });

    const { status, results, next_page_token, html_attributions } = response;
    // console.log(test.data.json());
    results = response.results[0];
    console.log(results);
  } catch (error) {
    console.log(error);
  }
`
when I print results, it says :
`
**"results" is read-only**
`

**Comment by mcabs3** [comment]
That is because you are trying to reassign results.

you destructure it `const { status, results...`

and then you try to reassign it `results = response.results[0];`

**Comment by PradyMagal** [comment]
So i reassigned my variable names just to clear any confusion, I am trying to store the results in a variable, but results1 prints undefined as well:

`var results1 = null;
 function search(){
     try {
    const response = places.nearbysearch({
      location: text, // LatLon delimited by ,
      radius: distance,  // Radius cannot be used if rankBy set to DISTANCE
      type: ['cafe','bakery','meal_delivery','meal_takeaway','restaurant'], // Undefined type will return all types
      // rankby: "distance" // See google docs for different possible values
    });

    const { status, results, next_page_token, html_attributions } = response;
    // console.log(test.data.json());
    results1 = response.results;
    console.log(results1);
  } catch (error) {
    console.log(error);
  }


 }`

**Comment by mcabs3** [comment]
Are you using `async/await`? nearbysearch is a promise so you either have to use `.then()` or `await`.

`places.nearbysearch({...}).then(response => {})`

or `const response = await places.nearbysearch({})`

**Comment by PradyMagal** [comment]
Async did the trick for picking out objects, but how exactly would I get different place details from there?

I tried assigning response.results.name to a variably but it printed undefined
`async function search() {
     try {
    const response = await places.nearbysearch({
      location: text, // LatLon delimited by ,
      radius: distance,  // Radius cannot be used if rankBy set to DISTANCE
      type: ['cafe','bakery','meal_delivery','meal_takeaway','restaurant'], // Undefined type will return all types
      // rankby: "distance" // See google docs for different possible values
    });

    const { status, results, next_page_token, html_attributions } = response;
    // console.log(test.data.json());

    results1 = response.results[1];
    console.log(results1);
    restName = results1.name;
    console.log(restName);
  } catch (error) {
    console.log(error);
  }


 }`

**Comment by mcabs3** [comment]
have you tried `console.log(results1)` to see what you get? or `console.log(reponse.results)`?

I am going to close this issue because it seems this is an issue of usage and not the library itself. I'll still try to help you if you need it.

**Comment by PradyMagal** [comment]
Ok so I've gotten access to the place results and details, but the variable is not updating

```
async function search() {
     try {
    const response = await places.nearbysearch({
      location: text, // LatLon delimited by ,
      radius: distance,  // Radius cannot be used if rankBy set to DISTANCE
      type: ['cafe','bakery','meal_delivery','meal_takeaway','restaurant'], // Undefined type will return all types
      // rankby: "distance" // See google docs for different possible values
    });

    const { status, results, next_page_token, html_attributions } = response;

    var index = Math.floor(Math.random() * response.results.length);
    console.log(response.results[index].name);
  
    restName = response.results[index].name;
    console.log(restName);
  
  } catch (error) {
    console.log(error);
  }


 }
```

it is within `export default function App() {}`

I have made a text compenent within view like this:
```
return (
    <View style={styles.container}>

    <View style={{minWidth: '100%', minHeight: '100%', backgroundColor: '#f0fbff', alignFit:'stretch', marginTop: 0, alignItems:'center', justifyContent:'space-evenly'}}>
    <Card style={{padding: 5, margin: 1}}>
      <Text style={{ fontWeight: 'bold', fontSize: 25,  }}>{restName}{"\n"}</Text>

```
even though restName updates( I made a button that runs the search() function on press), the text does not update, how would I implement set state with this or refresh the variabel.

**In short, the actual variable changes but it doesn't display anything differently**
