### ISSUE TITLE
NearbySearch rankby: distance broken

### ISSUE THREAD

**Issue by klapperkopp** [mcabs3/google-places-web#44]
According to [Places Docs](https://developers.google.com/maps/documentation/javascript/places#place_search_requests), the following applies:

> Note that you cannot specify a custom bounds and/or radius if you specify RankBy.DISTANCE

When I try to make a request like this, I am getting an error.
REQUEST:
`const response = await Places.nearbysearch({
        location: `52.5489798,13.3540563`,
        name: "REWE",
        type: "supermarket",
        rankby: "DISTANCE",
      });
`
Error: INVALID_REQUEST

However, when calling Google Places API directly, the request is valid and works. This is because radius should not be a required parameter when rankby ist set to "distance".

**Comment by mcabs3** [comment]
Nice fine, I will take a look. I apologize for the delay

**Comment by mcabs3** [comment]
looks like you'll need to use lowercase `distance` and not CAPS. the INVALID_REQUEST error is coming from the request itself and not from this library.
