### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by Jamongkad** [mcabs3/google-places-web#7]
<img width="261" alt="screen shot 2018-01-26 at 4 55 54 pm" src="https://user-images.githubusercontent.com/21994/35432065-d45e63aa-02b9-11e8-9b5d-f88d45f74478.png">

Getting Invalid API key warning despite passing valid Google API Key.

**Comment by Jesuskfc** [comment]
Im getting the same error and seem like there are not doc about this

**Comment by m4rtinsp** [comment]
Same problem here.
But the previous version works fine. I suggest using it until the author fixes the problem.

**Comment by mcabs3** [comment]
Sorry guys, I will look into this now.

**Comment by mcabs3** [comment]
I just published 0.1.3 that from my tests seem to address the issue. If you could please let me know if that addresses your issue that would be great. If you still are having issues, then please give me some more context and I will get to it asap.

**Comment by m4rtinsp** [comment]
@mcabs3 

My set:

```javascript
import Places from 'google-places-web'

Places.apiKey = Config.GOOGLE_PLACES_API_IOS
Places.debug = true

Places.autocomplete({ input: input, radius: 2000, language: 'pt_BR' })
      .then(results => {
        ...
      })
      .catch(e => console.log('error', e))
```

With version 0.1.1 - Everything is ok

With version 0.1.3 I get this error:

![google-places-web-error](https://user-images.githubusercontent.com/1391937/35645603-7be383d8-06b3-11e8-8781-59fad045a4c5.jpg)

**Comment by mcabs3** [comment]
@m4rtinsp I just ran your example locally (using 1.3 from npm) and I have it working successfully. Have you tried cleaning your `node_modules`? I'm here to help you figure this out.

That error is thrown here:

```javascript
_query(path, params) {
    const query = this._buildUri(path, params);
    return placesAxios.get(query)
      .then(response => {
        if (response.statusText === 'OK') {
          const json = response.data;
          this._log('JSON', JSON.stringify(json));
          if (json.status !== 'OK') {
            throw new Error(json.status);
          } else {
            return json;
          }
        }
        throw new Error(`HTTP ${response.status}`);
      });
  }
```

**Comment by m4rtinsp** [comment]
At that moment I just performed `yarn install google-places-web@0.1.3`
After your answer I killed my `node_modules` and installed everything again. But, Same problem :(

Debugging the `_query` method I noticed that the `response.statusText` is `undefined` so, changing to `response.data.status === 'OK'` works fine.

I'm running on iPhone 6 and iPad mini v1

see my `console.log`:

![captura de tela 2018-01-31 as 19 03 58](https://user-images.githubusercontent.com/1391937/35647612-38f82888-06ba-11e8-8772-c59fb262e497.png)

**Comment by mcabs3** [comment]
@m4rtinsp very interesting (and thanks for being patient), I bumped out a version 0.1.4 for you to try. The [response.statusText](https://github.com/axios/axios#response-schema) is coming from the Axios Response Schema, however since by default all 200 requests are ok, I can remove that `if` entirely. This is the snippet i'm testing with for your issue:

```javascript
import Places from 'google-places-web';

Places.apiKey = 'my-api-key';
Places.debug = true;

let partialAddress = 'rua Gabriel dos santos 132';
const radius = 2000;
const language = 'pt_BR';

// Search with default opts
Places.autocomplete({ input: partialAddress, radius, language })
  .then(results => {
    console.log('Results Found:', results.length)
  })
  .catch(e => console.log(e));
```

**Comment by m4rtinsp** [comment]
@mcabs3 Now, everything seems to work fine!
Thanks for your support!

**Comment by mcabs3** [comment]
@m4rtinsp wonderful! thanks again for helping! @Jamongkad please try out the 0.1.4 version and let me know if your problem persists.
