### ISSUE TITLE
Using 'textsearch' returns 'Unhandled Promise Rejection'.

### ISSUE THREAD

**Issue by imcrainjames** [mcabs3/google-places-web#8]
Calling the 'textsearch' method is working fine - nothing breaks, however, I am getting a lot of 'YellowBox' warnings in the console.

For every call to this method, the following warning is returned: `Unhandled Promise Rejection` and then `TypeError: cb is not a function`.

I am calling the method with a single instance of `Places`, so something like:

`googlePlaces.textsearch({ location: ..., radius: ..., query: ... }).then((results) => {}).catch((error) => {})`.

My 'catch' statement is *never triggered*, but I am getting the warning messages mentioned above. And, for what it is worth, it appears the Promise is handling the Promise Rejection with a `catch` statement, just that the `cb` being returned isn't a function.

Thanks in advance ...

**Comment by mcabs3** [comment]
Sorry for the delay, I will address this now.

**Comment by mcabs3** [comment]
If you upgrade to 0.1.5 your issue should be resolved, I attempted to do fallback support for callbacks, however clearly I have failed, I'll work on that feature separately. Thanks for your patience.

**Comment by imcrainjames** [comment]
Awesome. Works great. Thanks man.
