### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by Gillinghammer** [mcabs3/google-places-web#9]
Not sure why - but when I try and access Place details I am getting a CORS error. 

`Failed to load https://maps.googleapis.com/maps/api/place/details/json?key=XXXX&placeid=ChIJD3uTd9hx5kcR1IQvGfr8dbk: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`

**Comment by Gillinghammer** [comment]
Yes using create-react-app here - is that not supported?
Ended up using the googlemaps javascript api directly for now.

**Comment by mcabs3** [comment]
are you using a proxy or anything? It should work just fine with CRA. I just guessed because I've seen that problem with other libraries I have used. I'll try to help you figure it out.

**Comment by Gillinghammer** [comment]
No proxy just running my app on localhost:3000

Using this library for an autocomplete component, react-places-autocomplete . Maybe it's conflicting somehow?

**Comment by mcabs3** [comment]
I’ll spin up a CRA example to try and do the same thing and work it out. Stay tuned! And thanks for your patience

**Comment by Gillinghammer** [comment]
Thanks for taking a look I appreciate it... looks like a great handy library to use.

**Comment by mcabs3** [comment]
So I was able to recreate the issue. What I discovered is that I made a mistake, this library implements the JS SDK for Google Places, which is for the Node platform. I will work on creating a similar library for the web api to match this, but from my tests it looks like this will work for React Native and Node projects. I'm sorry for the inconvenience! I'll work on it asap!

**Comment by broskees** [comment]
Hey there, what happened with this?

**Comment by mcabs3** [comment]
This was closed due to the fact that this library is not made to be for the browser
